### ISSUE TITLE
npm link failing on prepublish

### ISSUE THREAD

**Issue by catesandrew** [iarna/in-publish#2]
npm v2.13.2
in-publish v2.0.0
package.json.scripts.prepublish = "in-publish && npm prune && npm shrinkwrap || in-install"

```
info generator-soto@0.1.0 Failed to exec prepublish script
verbose stack Error: generator-soto@0.1.0 prepublish: `in-publish && npm prune && npm shrinkwrap`
verbose stack Exit status 1
verbose stack     at EventEmitter.<anonymous> (/usr/local/nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
verbose stack     at EventEmitter.emit (events.js:110:17)
verbose stack     at ChildProcess.<anonymous> (/usr/local/nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/spawn.js:24:14)
verbose stack     at ChildProcess.emit (events.js:110:17)
verbose stack     at maybeClose (child_process.js:1015:16)
verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
verbose pkgid generator-soto@0.1.0
verbose cwd /usr/local/src/yeoman/generator-soto
error Darwin 14.4.0
error argv "node" "/usr/local/nvm/versions/node/v0.12.7/bin/npm" "link"
error node v0.12.7
error npm  v2.13.2
error code ELIFECYCLE
error generator-soto@0.1.0 prepublish: `in-publish && npm prune && npm shrinkwrap`
error Exit status 1
error Failed at the generator-soto@0.1.0 prepublish script 'in-publish && npm prune && npm shrinkwrap'.
```

i'm not doing anything weird or odd in the script. it works fine on npm install and npm publish. however, npm link triggers this issue. looks like an edge case. i'll try with a new project and try to replicate there.

**Comment by iarna** [comment]
Hey there, can you share your actual `package.json`?

I ask because you say:

> package.json.scripts.prepublish = "in-publish && npm prune && npm shrinkwrap || in-install"

Buuut....

```
verbose stack Error: generator-soto@0.1.0 prepublish: `in-publish && npm prune && npm shrinkwrap`
```

Says that npm isn't seeing that final `|| in-install`

**Comment by catesandrew** [comment]
that was  a copy/paste error, it wrapped. here's my package.json.

``` sh
79 info prepublish generator-soto@0.3.0
80 verbose unsafe-perm in lifecycle true
81 info generator-soto@0.3.0 Failed to exec prepublish script
82 verbose stack Error: generator-soto@0.3.0 prepublish: `in-publish && npm prune && npm shrinkwrap || in-install`
82 verbose stack Exit status 1
82 verbose stack     at EventEmitter.<anonymous> (/usr/local/nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
82 verbose stack     at EventEmitter.emit (events.js:110:17)
82 verbose stack     at ChildProcess.<anonymous> (/usr/local/nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/spawn.js:24:14)
82 verbose stack     at ChildProcess.emit (events.js:110:17)
82 verbose stack     at maybeClose (child_process.js:1015:16)
82 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
83 verbose pkgid generator-soto@0.3.0
84 verbose cwd /usr/local/src/ibaset/yeoman/generator-soto
85 error Darwin 14.4.0
86 error argv "node" "/usr/local/nvm/versions/node/v0.12.7/bin/npm" "link"
87 error node v0.12.7
88 error npm  v2.13.4
89 error code ELIFECYCLE
90 error generator-soto@0.3.0 prepublish: `in-publish && npm prune && npm shrinkwrap || in-install`
90 error Exit status 1
91 error Failed at the generator-soto@0.3.0 prepublish script 'in-publish && npm prune && npm shrinkwrap || in-install'.
```

``` json
"scripts": {
  "postinstall": "node bin/run-init-hooks",
  "prepublish": "in-publish && npm prune && npm shrinkwrap || in-install",
  "postpublish": "rimraf npm-shrinkwrap.json",
  "test": "$(npm bin)/hornet_mocha --harmony test/"
}
```

**Comment by iarna** [comment]
Ok, so I kind of forgot my own documentation here =D

As of in-publish@2.0.0, you should EITHER have:

```
in-publish && npm prune && npm shrinkwrap || not-in-publish
```

OR

```
not-in-install && npm prune && npm shrinkwrap || in-install
```

But you shouldn't mix the two. The `not-in-publish` and `not-in-install` helpers were added to specifically work around this sort of edge case.

**Comment by catesandrew** [comment]
```
in-publish && npm prune && npm shrinkwrap || not-in-publish
```

allowed `npm link` to work with no errors. thanks for the fix!
